spring:
    profiles:
        name: tradingsad
        active: prod
    datasource:
        url: jdbc:postgresql://db:5432/teste
        username: postgres
        password: tradingSAD42
#        schema: teste

server:
    port: 8081
    servlet:
        context-path: /api

#logging:
#    file: /var/log/cadastropessoas.log
#    level: INFO


